# Generated by Django 4.2.6 on 2024-03-17 18:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0003_bookmark_place_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bookmark",
            name="place_id",
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name="bookmark",
            name="place_name",
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name="review",
            name="place_id",
            field=models.CharField(max_length=300),
        ),
    ]
